version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: things
    ports:
    - 5432:5432
    expose:
    - "5432"
    volumes:
    - /database:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - 80:80
    restart: always

  tgbot:
    build: bot/
    restart: always
    expose:
    - "5432"
